### ISSUE TITLE
Links don't work anymore

### ISSUE THREAD

**Issue by jengeb** [pelias/polylines#151]
After clicking the links (e.g., https://s3.amazonaws.com/pelias-data/poylines/berlin.gz) in order to [download data](https://github.com/pelias/polylines#download-data) the following error message appears:

```xml
<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
...
```

As far as I can see the general [AWS status](https://status.aws.amazon.com/) doesn't show any anomalies.

**Comment by orangejulius** [comment]
Hey @jengeb 
This is yet another thing broken by the Mapzen shutdown. It should be fixed in https://github.com/pelias/polylines/pull/150

**Comment by jengeb** [comment]
Hi @orangejulius, 
Thanks for your very quick response. Sorry, I wasn't aware of this PR.

**Comment by orangejulius** [comment]
No worries, I had actually forgotten to merge it. So your reminder is welcome :)
