### ISSUE TITLE
Use host data path on the Docker container

### ISSUE THREAD

**Issue by Binternet** [pelias/polylines#158]
I'm trying to run the polyline as a Docker container, but the host already has all data pbf/oa data on it on `/data/pelias` folder, how can I point the docker to work with that folder?

**Comment by missinglink** [comment]
have a look at the docker documentation for the `-v` flag, this option allows you to expose directories on your local machine to the docker container.

**Comment by missinglink** [comment]
https://docs.docker.com/engine/reference/run/

**Comment by missinglink** [comment]
also https://github.com/pelias/interpolation#run-docker-image

**Comment by Binternet** [comment]
Thanks
