### ISSUE TITLE
PBF Extraction is killed - xargs: pbf: terminated by signal 9

### ISSUE THREAD

**Issue by Binternet** [pelias/polylines#166]
I am running polylines extractor inside a docker container while mapping the pbf from the host to the container:

`docker run -d -v /data/pelias:/data pelias/polylines /code/pelias/polylines/docker_extract.sh`

After quite a while the process is killed:
`xargs: pbf: terminated by signal 9`

The process is running on a `c4.4xlarge` instance with 30GB of RAM

**Comment by missinglink** [comment]
Hi Lior, could you please post the filename and filesize of the `.pbf` files you are using.

**Comment by Binternet** [comment]
39G planet-latest.osm.pbf

**Comment by missinglink** [comment]
agh yep, as I suspected, the dockerfile setup wont currently work to convert the planet file.

I added https://github.com/pelias/polylines/pull/167 this morning and https://github.com/missinglink/pbf/pull/15 a few weeks ago but we use the method documented here: https://github.com/pelias/polylines/wiki/Generating-polylines-from-Valhalla to build the polylines file required for https://geocode.earth builds.

The easiest option is to just use the planet-wide polyline extract I published in 2017, the link is in the readme: https://github.com/pelias/polylines#download-data

You just need to download and extract that file and rename it `/data/pelias/openstreetmap/extract.0sv`, then you can skip the `docker_extract.sh` entirely.

**Comment by Binternet** [comment]
If you're referring to [this link](https://s3.amazonaws.com/pelias-data.nextzen.org/poylines/road_network.gz) then it's broken..any other valid sources?

**Comment by Binternet** [comment]
Should I try running the extraction command from the PBF on the instance itself without docker?

**Comment by missinglink** [comment]
odd, the correct URL is https://s3-us-east-2.amazonaws.com/pelias-data.nextzen.org/poylines/road_network.gz

I'll update the docs.

**Comment by missinglink** [comment]
Looks like the bucket was moved from `us-east-1` to `us-east-2`, we are going to move it back to `us-east-1` instead of changing the docs.

**Comment by missinglink** [comment]
Please grab a copy of that file from the `us-east-2` bucket while you can, we will be moving the bucket later today and the data will be unavailable for a couple hours while it's being moved between data centers.

**Comment by Binternet** [comment]
Download stuck on 1.0GB, can you ping me once its available on us-east-1? i'll try again in ~11 hours

**Comment by missinglink** [comment]
works for me, try this url (seems to be region agnostic): http://pelias-data.nextzen.org.s3.amazonaws.com/poylines/road_network.gz

**Comment by missinglink** [comment]
also the typo this this dir name drives me crazy, I'll add a task to fix that while we're doing this work :)

**Comment by Binternet** [comment]
OK, got the file, thanks!
