### ISSUE TITLE
Polyline planet data download link is offline

### ISSUE THREAD

**Issue by fheyen** [pelias/polylines#170]
The link to the full planet polylines (http://pelias-data.nextzen.org.s3.amazonaws.com/poylines/road_network.gz) does not work anymore.
Is the data available somewhere else? If not I will try this: https://github.com/pelias/polylines/wiki/Generating-polylines-from-Valhalla
I think you may want to update the file https://github.com/pelias/polylines#download-data in any case.

**Comment by fheyen** [comment]
I just realized that the data is online and there is just a typo in the URL (poylines).

**Comment by orangejulius** [comment]
Yes, funny story, we fixed the typo recently, but did not update the link. Feel free to submit a PR, or we'll get to it soon.

**Comment by orangejulius** [comment]
Hey @fheyen,
We almost forgot about this completely, but please check out the changes in https://github.com/pelias/polylines/pull/184, it should fix all the links.
