### ISSUE TITLE
Update provided road_network file for world

### ISSUE THREAD

**Issue by otbutz** [pelias/polylines#214]
The current (example?) road_network file provided by https://s3.amazonaws.com/pelias-data.nextzen.org/polylines/road_network.gz is a bit outdated.

I'm currently thinking about generating a new version using the current OSM world dataset. Would you be interested in the generated file?

**Comment by missinglink** [comment]
Hi @otbutz, we have scripts which generate this file regularly for [geocode.earth](https://geocode.earth), no need to generate one, I'll see if I can copy one of our recent files across to the nextzen bucket.

**Comment by missinglink** [comment]
You can now download a current extract from our new hosted data page https://geocode.earth/data

I'll update the README to reflect this
