### ISSUE TITLE
not able to run ERROR invalid Action type. Must be `func(*Context`)` or `func(*Context) error).

### ISSUE THREAD

**Issue by luca-saggese** [pelias/polylines#227]
I'm new to go, so please forget if i say something stupid.
i'm trying to modify your code to add more information to the poly line extraction, but when i run the modified program i get:
ERROR invalid Action type. Must be `func(*Context`)` or `func(*Context) error).

go version
go version go1.12.6 linux/amd64

go run pbf.go streets ../data/centro-latest.osm.pbf 
ERROR invalid Action type. Must be `func(*Context`)` or `func(*Context) error).  This is an error in the application.  Please contact the distributor of this application if this is not you.See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
exit status 2

getting your code directly with go get does it work.

Please help

**Comment by missinglink** [comment]
Hi, I think this is the wrong repo?

**Comment by missinglink** [comment]
I'm not sure what the issues is, can you please update the dependencies using `go get`.

Looking at the code it seems that it's using one of the suggested method signatures...

https://github.com/missinglink/pbf/blob/master/command/street_merge.go#L90

**Comment by missinglink** [comment]
Please post a diff of your changes

**Comment by luca-saggese** [comment]
Sorry i posted on the wrong repo, was on pbf one, anyway it was a problem of my go installation, solved using docker image of goland.
thanks
