### ISSUE TITLE
Is prepare polylines absolutely needed for geocoding purposes?

### ISSUE THREAD

**Issue by shekoufa** [pelias/polylines#242]
Hey team! 

I have a problem to solve using Pelias and it's just as simple as geocoding some strings of addresses (well it honestly just sounds simple!!). prepare polylines is a really time-consuming process when building the entire planet. Looking at the readme for Polylines, it says: "The polyline importer facilitates importing road network data into Pelias from a list of polyline encoded line strings." 
As far as I know, for my use-case, I wouldn't be concerned about road data. The only thing I need, as I said, is to geocode some specific addresses. With this in mind, can I skip the step "prepare polylines" safely without losing any functionalities that I would need for my use-case?

**Comment by missinglink** [comment]
Yes you can skip the polylines steps which just mean you'll have nothing in the `street` layer.

**Comment by missinglink** [comment]
Another option is to just grab the data from our servers which we provide free of charge: https://geocode.earth/data

**Comment by missinglink** [comment]
Hope that helps, I'm going to go ahead and close this issue.

**Comment by orangejulius** [comment]
One additional note: street data is required for the interpolation service to function: without street data imported into Elasticsearch, Pelias doesn't have the information needed to call the interpolation service correctly.

In our experience, the interpolation service doesn't bring a _huge_ improvement, but if ensuring more accurate results is worth additional setup complexity, then you might find it worth it.

**Comment by missinglink** [comment]
Oh yes, good point, the interpolation service only works in the case that the user requested an address but we had to fall-back to a street, if you have no streets then this will never happen.

In your specific case this might make a huge difference to the quality of results.
