### ISSUE TITLE
Proposal: rename this repo `polyline`

### ISSUE THREAD

**Issue by orangejulius** [pelias/polylines#4]
All our other importers are singular, and the config file option being read from is also singular:

See [line 28 in bin/cli.js](https://github.com/pelias/polylines/blob/master/bin/cli.js#L28):

```js
if( !!argv.config ){
  var cfg = config.generate();
  if( cfg.imports.polyline && cfg.imports.polyline.datapath && cfg.imports.polyline.files[0] ){
    argv.file = path.join( cfg.imports.polyline.datapath, cfg.imports.polyline.files[0] );
  }
}```

**Comment by missinglink** [comment]
A 'polyline' represents a single road segment, 'polylines' are a collection of these entries.

**Comment by missinglink** [comment]
Renaming it will require going through other repos such as config and chef-mapzen-pelias to make the changes there too.

If you feel strongly enough about it then I have no objections.

**Comment by missinglink** [comment]
Well apparently not config, I agree that is inconsistent and should probably be fixed

**Comment by missinglink** [comment]
I'm actually fine with renaming this, I did give it some though when naming it but I agree that `polylines` doesn't have a great ring to it.

I chose the plural version in order to be consistent with the other datasets `geonames` `quattroshapes` and `openaddresses` which are all plural.

**Comment by dianashk** [comment]
If we're going to rename, should we consider naming it something other than polylines too? Maybe streets or roads? Not a lot of people will know what polyline(s) are.

**Comment by orangejulius** [comment]
Oh, maybe the repo name is fine to be plural, I forgot the others were plural. Then we just have some fine tuning to do of the config variables, which is much easier.
