### ISSUE TITLE
Make note in README to use "polyline" (singular) in ~/pelias.json file

### ISSUE THREAD

**Issue by tigerlily-he** [pelias/polylines#73]
Under the configuration section, there is code snippet on setting up the configuration file. 
```json
"imports": {
    "polyline": {
      "adminLookup": true,
      "datapath": "/data",
      "files": [ "road_network.polylines" ]
    }
  }
```
 Point of confusion: The repo name is pluralized, however the configuration file needs the name to be singular. It will not run if polylines (pural) is used. 

Brought up in https://github.com/pelias/polylines/issues/4 but closed.

**Comment by orangejulius** [comment]
:+1: We could also add something to the Joi schema that warns if someone uses the wrong configuration section name.
